//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redmine.Client.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redmine.Client.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires authentication.
        /// </summary>
        internal static string AuthenticationCheckBox {
            get {
                return ResourceManager.GetString("AuthenticationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string BtnAboutButton {
            get {
                return ResourceManager.GetString("BtnAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string BtnCommitButton {
            get {
                return ResourceManager.GetString("BtnCommitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string BtnExitButton {
            get {
                return ResourceManager.GetString("BtnExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string BtnNewIssueButton {
            get {
                return ResourceManager.GetString("BtnNewIssueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string BtnRefreshButton {
            get {
                return ResourceManager.GetString("BtnRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string BtnResetButton {
            get {
                return ResourceManager.GetString("BtnResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string BtnSettingsButton {
            get {
                return ResourceManager.GetString("BtnSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string BtnStartButton {
            get {
                return ResourceManager.GetString("BtnStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string BtnStartButton_Pause {
            get {
                return ResourceManager.GetString("BtnStartButton_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string labelActivity {
            get {
                return ResourceManager.GetString("labelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string labelComment {
            get {
                return ResourceManager.GetString("labelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string labelProject {
            get {
                return ResourceManager.GetString("labelProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine password.
        /// </summary>
        internal static string labelRedminePassword {
            get {
                return ResourceManager.GetString("labelRedminePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine URL.
        /// </summary>
        internal static string labelRedmineURL {
            get {
                return ResourceManager.GetString("labelRedmineURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine username.
        /// </summary>
        internal static string labelRedmineUsername {
            get {
                return ResourceManager.GetString("labelRedmineUsername", resourceCulture);
            }
        }
    }
}
