//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redmine.Client.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redmine.Client.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string addNewToolStripMenuItem {
            get {
                return ResourceManager.GetString("addNewToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note when changing the status with above options.
        /// </summary>
        internal static string AddNoteOnChangeCheckBox {
            get {
                return ResourceManager.GetString("AddNoteOnChangeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.0.x.
        /// </summary>
        internal static string ApiVersion_V10x {
            get {
                return ResourceManager.GetString("ApiVersion_V10x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.1.x.
        /// </summary>
        internal static string ApiVersion_V11x {
            get {
                return ResourceManager.GetString("ApiVersion_V11x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.2.x.
        /// </summary>
        internal static string ApiVersion_V12x {
            get {
                return ResourceManager.GetString("ApiVersion_V12x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.3.x.
        /// </summary>
        internal static string ApiVersion_V13x {
            get {
                return ResourceManager.GetString("ApiVersion_V13x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.4.x.
        /// </summary>
        internal static string ApiVersion_V14x {
            get {
                return ResourceManager.GetString("ApiVersion_V14x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2.0.x.
        /// </summary>
        internal static string ApiVersion_V20x {
            get {
                return ResourceManager.GetString("ApiVersion_V20x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2.1.x.
        /// </summary>
        internal static string ApiVersion_V21x {
            get {
                return ResourceManager.GetString("ApiVersion_V21x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2.2.x.
        /// </summary>
        internal static string ApiVersion_V22x {
            get {
                return ResourceManager.GetString("ApiVersion_V22x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires authentication.
        /// </summary>
        internal static string AuthenticationCheckBox {
            get {
                return ResourceManager.GetString("AuthenticationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string BgWork_CheckUpdates {
            get {
                return ResourceManager.GetString("BgWork_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving form data.
        /// </summary>
        internal static string BgWork_GetFormData {
            get {
                return ResourceManager.GetString("BgWork_GetFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Issue information.
        /// </summary>
        internal static string BgWork_GetIssue {
            get {
                return ResourceManager.GetString("BgWork_GetIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Time Entries.
        /// </summary>
        internal static string BgWork_GetTimeEntries {
            get {
                return ResourceManager.GetString("BgWork_GetTimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving user name.
        /// </summary>
        internal static string BgWork_GetUsername {
            get {
                return ResourceManager.GetString("BgWork_GetUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string BtnAboutButton {
            get {
                return ResourceManager.GetString("BtnAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string BtnAddButton {
            get {
                return ResourceManager.GetString("BtnAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BtnBrowseButton {
            get {
                return ResourceManager.GetString("BtnBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancelButton {
            get {
                return ResourceManager.GetString("BtnCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BtnClearButton {
            get {
                return ResourceManager.GetString("BtnClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Issue.
        /// </summary>
        internal static string BtnCloseButton {
            get {
                return ResourceManager.GetString("BtnCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string BtnCommitButton {
            get {
                return ResourceManager.GetString("BtnCommitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BtnDeleteButton {
            get {
                return ResourceManager.GetString("BtnDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string BtnEditActivitiesButton {
            get {
                return ResourceManager.GetString("BtnEditActivitiesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Cat..
        /// </summary>
        internal static string BtnEditDocumentCategories {
            get {
                return ResourceManager.GetString("BtnEditDocumentCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorities.
        /// </summary>
        internal static string BtnEditIssuePriorities {
            get {
                return ResourceManager.GetString("BtnEditIssuePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string BtnExitButton {
            get {
                return ResourceManager.GetString("BtnExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string BtnModifyButton {
            get {
                return ResourceManager.GetString("BtnModifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string BtnNewIssueButton {
            get {
                return ResourceManager.GetString("BtnNewIssueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOKButton {
            get {
                return ResourceManager.GetString("BtnOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string BtnRefreshButton {
            get {
                return ResourceManager.GetString("BtnRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string BtnRefreshButton_Filter {
            get {
                return ResourceManager.GetString("BtnRefreshButton_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string BtnResetButton {
            get {
                return ResourceManager.GetString("BtnResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnSaveButton {
            get {
                return ResourceManager.GetString("BtnSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string BtnSettingsButton {
            get {
                return ResourceManager.GetString("BtnSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string BtnStartButton {
            get {
                return ResourceManager.GetString("BtnStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string BtnStartButton_Pause {
            get {
                return ResourceManager.GetString("BtnStartButton_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string BtnTestConnection {
            get {
                return ResourceManager.GetString("BtnTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Time.
        /// </summary>
        internal static string BtnViewTimeButton {
            get {
                return ResourceManager.GetString("BtnViewTimeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string cbDueDate {
            get {
                return ResourceManager.GetString("cbDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string cbStartDate {
            get {
                return ResourceManager.GetString("cbStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also close the issue.
        /// </summary>
        internal static string CheckBoxClosesIssue {
            get {
                return ResourceManager.GetString("CheckBoxClosesIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Show Issues assigned to Me.
        /// </summary>
        internal static string CheckBoxOnlyMe {
            get {
                return ResourceManager.GetString("CheckBoxOnlyMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        internal static string CheckForUpdatesCheckBox {
            get {
                return ResourceManager.GetString("CheckForUpdatesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close issue {0}?.
        /// </summary>
        internal static string CloseIssueText {
            get {
                return ResourceManager.GetString("CloseIssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the new comment?.
        /// </summary>
        internal static string CommitCancelSaveCommentQuestion {
            get {
                return ResourceManager.GetString("CommitCancelSaveCommentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cancelled committing your spent time, but changed the comment.{0}Do you want to use the new comment?.
        /// </summary>
        internal static string CommitCancelSaveCommentText {
            get {
                return ResourceManager.GetString("CommitCancelSaveCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to commit?.
        /// </summary>
        internal static string CommitConfirmQuestion {
            get {
                return ResourceManager.GetString("CommitConfirmQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to commit the following entry: {6} Project: {0}, Activity: {1}, Issue: {2},{6}Date: {3}, Comment: {4}, Time: {5}.
        /// </summary>
        internal static string CommitConfirmText {
            get {
                return ResourceManager.GetString("CommitConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no activity selected..
        /// </summary>
        internal static string CommitNoActivitySelected {
            get {
                return ResourceManager.GetString("CommitNoActivitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no issue selected..
        /// </summary>
        internal static string CommitNoIssueSelected {
            get {
                return ResourceManager.GetString("CommitNoIssueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no time to log....
        /// </summary>
        internal static string CommitNoTime {
            get {
                return ResourceManager.GetString("CommitNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work logged successfully..
        /// </summary>
        internal static string CommitSuccessfullText {
            get {
                return ResourceManager.GetString("CommitSuccessfullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work logged.
        /// </summary>
        internal static string CommitSuccessfullTitle {
            get {
                return ResourceManager.GetString("CommitSuccessfullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating the connection with Redmine failed. The following error occurred: {0}.
        /// </summary>
        internal static string ConnectionTestFailed_Text {
            get {
                return ResourceManager.GetString("ConnectionTestFailed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test Failed.
        /// </summary>
        internal static string ConnectionTestFailed_Title {
            get {
                return ResourceManager.GetString("ConnectionTestFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating the connection with Redmine was successful..
        /// </summary>
        internal static string ConnectionTestOK_Text {
            get {
                return ResourceManager.GetString("ConnectionTestOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test Success.
        /// </summary>
        internal static string ConnectionTestOK_Title {
            get {
                return ResourceManager.GetString("ConnectionTestOK_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new attachment for issue {0} {1}.
        /// </summary>
        internal static string DlgAttachmentTitle {
            get {
                return ResourceManager.GetString("DlgAttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enumeration Value {0} for {1}.
        /// </summary>
        internal static string DlgEditEnumFormTitle_Edit {
            get {
                return ResourceManager.GetString("DlgEditEnumFormTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Enumeration Value for {0}.
        /// </summary>
        internal static string DlgEditEnumFormTitle_New {
            get {
                return ResourceManager.GetString("DlgEditEnumFormTitle_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enumeration {0}.
        /// </summary>
        internal static string DlgEditEnumListFormTitle {
            get {
                return ResourceManager.GetString("DlgEditEnumListFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Issue {0} for project {1}.
        /// </summary>
        internal static string DlgIssueTitleEdit {
            get {
                return ResourceManager.GetString("DlgIssueTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Issue for project {0}.
        /// </summary>
        internal static string DlgIssueTitleNew {
            get {
                return ResourceManager.GetString("DlgIssueTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string DlgSettingsTitle {
            get {
                return ResourceManager.GetString("DlgSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View time-entries of issue {0} {1}.
        /// </summary>
        internal static string DlgTimeEntriesTitle {
            get {
                return ResourceManager.GetString("DlgTimeEntriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Time entry of {0} for issue {1} {2}.
        /// </summary>
        internal static string DlgTimeEntryFormTitle_Edit {
            get {
                return ResourceManager.GetString("DlgTimeEntryFormTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Time Entry for issue {0} {1}.
        /// </summary>
        internal static string DlgTimeEntryFormTitle_New {
            get {
                return ResourceManager.GetString("DlgTimeEntryFormTitle_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating issue {0} {1}.
        /// </summary>
        internal static string DlgUpdateIssueNoteTitle {
            get {
                return ResourceManager.GetString("DlgUpdateIssueNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download / Open.
        /// </summary>
        internal static string downloadOpenToolStripMenuItem {
            get {
                return ResourceManager.GetString("downloadOpenToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Visible Columns.
        /// </summary>
        internal static string editVisibleColumnsHeaderToolStripMenuItem {
            get {
                return ResourceManager.GetString("editVisibleColumnsHeaderToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Visible Columns.
        /// </summary>
        internal static string editVisibleColumnsToolStripMenuItem {
            get {
                return ResourceManager.GetString("editVisibleColumnsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string EnumName_Activities {
            get {
                return ResourceManager.GetString("EnumName_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Categories.
        /// </summary>
        internal static string EnumName_DocumentCategories {
            get {
                return ResourceManager.GetString("EnumName_DocumentCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Priorities.
        /// </summary>
        internal static string EnumName_IssuePriorities {
            get {
                return ResourceManager.GetString("EnumName_IssuePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status used to close an issue is unknown, please go to settings to set this..
        /// </summary>
        internal static string Error_ClosedStatusUnknown {
            get {
                return ResourceManager.GetString("Error_ClosedStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the issue failed; The server responded: {0}.
        /// </summary>
        internal static string Error_CreateIssueFailed {
            get {
                return ResourceManager.GetString("Error_CreateIssueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}  is a mandatory field..
        /// </summary>
        internal static string Error_EnumFieldIsMandatory {
            get {
                return ResourceManager.GetString("Error_EnumFieldIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id and the Name must be unique..
        /// </summary>
        internal static string Error_EnumMustBeUnique {
            get {
                return ResourceManager.GetString("Error_EnumMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL of Redmine installation..
        /// </summary>
        internal static string Error_InvalidUrl {
            get {
                return ResourceManager.GetString("Error_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue subject is mandatory.
        /// </summary>
        internal static string Error_IssueSubjectMandatory {
            get {
                return ResourceManager.GetString("Error_IssueSubjectMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statusus used to update a new status to an in progress status of an issue are unknown, please go to settings to set those..
        /// </summary>
        internal static string Error_NewOrInProgressStatusUnknown {
            get {
                return ResourceManager.GetString("Error_NewOrInProgressStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects found in Redmine..
        /// </summary>
        internal static string Error_NoProjectsFound {
            get {
                return ResourceManager.GetString("Error_NoProjectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup error. Check Configuration..
        /// </summary>
        internal static string Error_Startup {
            get {
                return ResourceManager.GetString("Error_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the issue failed; The server responded: {0}.
        /// </summary>
        internal static string Error_UpdateIssueFailed {
            get {
                return ResourceManager.GetString("Error_UpdateIssueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value out of range.
        /// </summary>
        internal static string Error_ValueOutOfRange {
            get {
                return ResourceManager.GetString("Error_ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string groupBoxAttachments {
            get {
                return ResourceManager.GetString("groupBoxAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string groupBoxFilter {
            get {
                return ResourceManager.GetString("groupBoxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string GrpApplicationSettings {
            get {
                return ResourceManager.GetString("GrpApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enumerations.
        /// </summary>
        internal static string GrpEditEnumerations {
            get {
                return ResourceManager.GetString("GrpEditEnumerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Server Settings.
        /// </summary>
        internal static string GrpRedmineServerSettings {
            get {
                return ResourceManager.GetString("GrpRedmineServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        internal static string IssueField_assignedto {
            get {
                return ResourceManager.GetString("IssueField_assignedto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string IssueField_author {
            get {
                return ResourceManager.GetString("IssueField_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string IssueField_category {
            get {
                return ResourceManager.GetString("IssueField_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string IssueField_createdon {
            get {
                return ResourceManager.GetString("IssueField_createdon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string IssueField_description {
            get {
                return ResourceManager.GetString("IssueField_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Ratio.
        /// </summary>
        internal static string IssueField_doneratio {
            get {
                return ResourceManager.GetString("IssueField_doneratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string IssueField_duedate {
            get {
                return ResourceManager.GetString("IssueField_duedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Hours.
        /// </summary>
        internal static string IssueField_estimatedhours {
            get {
                return ResourceManager.GetString("IssueField_estimatedhours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Version.
        /// </summary>
        internal static string IssueField_fixedversion {
            get {
                return ResourceManager.GetString("IssueField_fixedversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string IssueField_id {
            get {
                return ResourceManager.GetString("IssueField_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Issue.
        /// </summary>
        internal static string IssueField_parentissue {
            get {
                return ResourceManager.GetString("IssueField_parentissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string IssueField_priority {
            get {
                return ResourceManager.GetString("IssueField_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string IssueField_project {
            get {
                return ResourceManager.GetString("IssueField_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string IssueField_startdate {
            get {
                return ResourceManager.GetString("IssueField_startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string IssueField_status {
            get {
                return ResourceManager.GetString("IssueField_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string IssueField_subject {
            get {
                return ResourceManager.GetString("IssueField_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        internal static string IssueField_tracker {
            get {
                return ResourceManager.GetString("IssueField_tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        internal static string IssueField_updatedon {
            get {
                return ResourceManager.GetString("IssueField_updatedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current selected issue {0} is updated to the &apos;In Progress&apos; state. (StatusId = {1}).
        /// </summary>
        internal static string IssueUpdatedToInProgress {
            get {
                return ResourceManager.GetString("IssueUpdatedToInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string labelActivity {
            get {
                return ResourceManager.GetString("labelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        internal static string labelAssignedTo {
            get {
                return ResourceManager.GetString("labelAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string labelAttachmentDescription {
            get {
                return ResourceManager.GetString("labelAttachmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By User.
        /// </summary>
        internal static string labelByUser {
            get {
                return ResourceManager.GetString("labelByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache lifetime (minutes, 0 = infinite).
        /// </summary>
        internal static string labelCacheLifetime {
            get {
                return ResourceManager.GetString("labelCacheLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string labelCategory {
            get {
                return ResourceManager.GetString("labelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children:.
        /// </summary>
        internal static string LabelChildren {
            get {
                return ResourceManager.GetString("LabelChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string labelComment {
            get {
                return ResourceManager.GetString("labelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity:.
        /// </summary>
        internal static string labelCommitActivity {
            get {
                return ResourceManager.GetString("labelCommitActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string labelCommitComment {
            get {
                return ResourceManager.GetString("labelCommitComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent on:.
        /// </summary>
        internal static string labelCommitDateSpent {
            get {
                return ResourceManager.GetString("labelCommitDateSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue:.
        /// </summary>
        internal static string labelCommitIssue {
            get {
                return ResourceManager.GetString("labelCommitIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        internal static string labelCommitProject {
            get {
                return ResourceManager.GetString("labelCommitProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to commit the following time entry?.
        /// </summary>
        internal static string labelCommitQuestion {
            get {
                return ResourceManager.GetString("labelCommitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (H):.
        /// </summary>
        internal static string labelCommitTime {
            get {
                return ResourceManager.GetString("labelCommitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string labelEnumId {
            get {
                return ResourceManager.GetString("labelEnumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string labelEnumName {
            get {
                return ResourceManager.GetString("labelEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        internal static string labelEstimatedTime {
            get {
                return ResourceManager.GetString("labelEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable fields with &apos;Test Connection&apos; and version V1.3.x or higher.
        /// </summary>
        internal static string labelExplClosingIssueStatus {
            get {
                return ResourceManager.GetString("labelExplClosingIssueStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string labelLanguage {
            get {
                return ResourceManager.GetString("labelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent: {0} {1}.
        /// </summary>
        internal static string LabelParent {
            get {
                return ResourceManager.GetString("LabelParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Done.
        /// </summary>
        internal static string labelPercentDone {
            get {
                return ResourceManager.GetString("labelPercentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup window when minimized
        ///or Request attention every
        ///(minutes, 0 = never).
        /// </summary>
        internal static string labelPopupTimout {
            get {
                return ResourceManager.GetString("labelPopupTimout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string labelPriority {
            get {
                return ResourceManager.GetString("labelPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string labelProject {
            get {
                return ResourceManager.GetString("labelProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine password.
        /// </summary>
        internal static string labelRedminePassword {
            get {
                return ResourceManager.GetString("labelRedminePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine URL.
        /// </summary>
        internal static string labelRedmineURL {
            get {
                return ResourceManager.GetString("labelRedmineURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine username / API Key.
        /// </summary>
        internal static string labelRedmineUsername {
            get {
                return ResourceManager.GetString("labelRedmineUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Version.
        /// </summary>
        internal static string labelRedmineVersion {
            get {
                return ResourceManager.GetString("labelRedmineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations.
        /// </summary>
        internal static string LabelRelations {
            get {
                return ResourceManager.GetString("LabelRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment File.
        /// </summary>
        internal static string labelSelectAttachment {
            get {
                return ResourceManager.GetString("labelSelectAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When closing an Issue, set it to.
        /// </summary>
        internal static string labelSelectCloseStatus {
            get {
                return ResourceManager.GetString("labelSelectCloseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent Hours.
        /// </summary>
        internal static string labelSpentHours {
            get {
                return ResourceManager.GetString("labelSpentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent On.
        /// </summary>
        internal static string labelSpentOn {
            get {
                return ResourceManager.GetString("labelSpentOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string labelSubject {
            get {
                return ResourceManager.GetString("labelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Version.
        /// </summary>
        internal static string labelTargetVersion {
            get {
                return ResourceManager.GetString("labelTargetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Time entry of {0} for issue{3}{1} {2}.
        /// </summary>
        internal static string labelTimeEntryTitle_Edit {
            get {
                return ResourceManager.GetString("labelTimeEntryTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Time Entry for issue{3}{0} {1}.
        /// </summary>
        internal static string labelTimeEntryTitle_New {
            get {
                return ResourceManager.GetString("labelTimeEntryTitle_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        internal static string labelTracker {
            get {
                return ResourceManager.GetString("labelTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional notes explaning your change - leave empty if none.
        /// </summary>
        internal static string labelUpdateIssueNote {
            get {
                return ResourceManager.GetString("labelUpdateIssueNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this issue in Redmine.
        /// </summary>
        internal static string linkEditInRedmine {
            get {
                return ResourceManager.GetString("linkEditInRedmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on start timer.
        /// </summary>
        internal static string MinimizeOnStartTimerCheckBox {
            get {
                return ResourceManager.GetString("MinimizeOnStartTimerCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to systemtray.
        /// </summary>
        internal static string MinimizeToSystemTrayCheckBox {
            get {
                return ResourceManager.GetString("MinimizeToSystemTrayCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New issue.
        /// </summary>
        internal static string NewIssue {
            get {
                return ResourceManager.GetString("NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available. Do you want me to take you to the download location?.
        /// </summary>
        internal static string NewVersionText {
            get {
                return ResourceManager.GetString("NewVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersionTitle {
            get {
                return ResourceManager.GetString("NewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Issue in &amp;Browser.
        /// </summary>
        internal static string openIssueInBrowserToolStripMenuItem {
            get {
                return ResourceManager.GetString("openIssueInBrowserToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Issue.
        /// </summary>
        internal static string openIssueToolStripMenuItem {
            get {
                return ResourceManager.GetString("openIssueToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause timer on screen lock and on logoff.
        /// </summary>
        internal static string PauseTimerOnLockCheckBox {
            get {
                return ResourceManager.GetString("PauseTimerOnLockCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string PauseToolStripMenuItem {
            get {
                return ResourceManager.GetString("PauseToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Client.
        /// </summary>
        internal static string RedmineClientTitle_NoUser {
            get {
                return ResourceManager.GetString("RedmineClientTitle_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Client - {0} {1}.
        /// </summary>
        internal static string RedmineClientTitle_User {
            get {
                return ResourceManager.GetString("RedmineClientTitle_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string RestoreToolStrip_Hide {
            get {
                return ResourceManager.GetString("RestoreToolStrip_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi&amp;nimize.
        /// </summary>
        internal static string RestoreToolStrip_Minimize {
            get {
                return ResourceManager.GetString("RestoreToolStrip_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore.
        /// </summary>
        internal static string RestoreToolStrip_Restore {
            get {
                return ResourceManager.GetString("RestoreToolStrip_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all issues.
        /// </summary>
        internal static string ShowAllIssues {
            get {
                return ResourceManager.GetString("ShowAllIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string StartToolStripMenuItem {
            get {
                return ResourceManager.GetString("StartToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Timer was ticking when you stopped the client. Do you want the client to continue ticking?.
        /// </summary>
        internal static string Timer_WasTickingWhenClosed {
            get {
                return ResourceManager.GetString("Timer_WasTickingWhenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted ({1}).
        /// </summary>
        internal static string UpdatedField_Deleted {
            get {
                return ResourceManager.GetString("UpdatedField_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description has been updated.
        /// </summary>
        internal static string UpdatedField_Description {
            get {
                return ResourceManager.GetString("UpdatedField_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set to {2}.
        /// </summary>
        internal static string UpdatedField_SetTo {
            get {
                return ResourceManager.GetString("UpdatedField_SetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed from {1} to {2}.
        /// </summary>
        internal static string UpdatedField_UpdatedTo {
            get {
                return ResourceManager.GetString("UpdatedField_UpdatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If timer starts and issue has state.
        /// </summary>
        internal static string UpdateIssueIfStateCheckBox {
            get {
                return ResourceManager.GetString("UpdateIssueIfStateCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then set the state to.
        /// </summary>
        internal static string UpdateIssueIfStateLabel {
            get {
                return ResourceManager.GetString("UpdateIssueIfStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete time entry {0}.
        /// </summary>
        internal static string Warning_AreYouSureDeleteTimeEntry {
            get {
                return ResourceManager.GetString("Warning_AreYouSureDeleteTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Redmine Client is trying to stop, but you are measuring your spent time.{0}Do you want to commit the time?.
        /// </summary>
        internal static string Warning_ClosingSaveTimes {
            get {
                return ResourceManager.GetString("Warning_ClosingSaveTimes", resourceCulture);
            }
        }
    }
}
