//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redmine.Client.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redmine.Client.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.0.x.
        /// </summary>
        internal static string ApiVersion_V10x {
            get {
                return ResourceManager.GetString("ApiVersion_V10x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.1.x.
        /// </summary>
        internal static string ApiVersion_V11x {
            get {
                return ResourceManager.GetString("ApiVersion_V11x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.3.x.
        /// </summary>
        internal static string ApiVersion_V13x {
            get {
                return ResourceManager.GetString("ApiVersion_V13x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.4.x.
        /// </summary>
        internal static string ApiVersion_V14x {
            get {
                return ResourceManager.GetString("ApiVersion_V14x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2.1.x.
        /// </summary>
        internal static string ApiVersion_V21x {
            get {
                return ResourceManager.GetString("ApiVersion_V21x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires authentication.
        /// </summary>
        internal static string AuthenticationCheckBox {
            get {
                return ResourceManager.GetString("AuthenticationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string BgWork_CheckUpdates {
            get {
                return ResourceManager.GetString("BgWork_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving form data.
        /// </summary>
        internal static string BgWork_GetFormData {
            get {
                return ResourceManager.GetString("BgWork_GetFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving user name.
        /// </summary>
        internal static string BgWork_GetUsername {
            get {
                return ResourceManager.GetString("BgWork_GetUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string BtnAboutButton {
            get {
                return ResourceManager.GetString("BtnAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string BtnAddButton {
            get {
                return ResourceManager.GetString("BtnAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancelButton {
            get {
                return ResourceManager.GetString("BtnCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Issue.
        /// </summary>
        internal static string BtnCloseButton {
            get {
                return ResourceManager.GetString("BtnCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string BtnCommitButton {
            get {
                return ResourceManager.GetString("BtnCommitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BtnDeleteButton {
            get {
                return ResourceManager.GetString("BtnDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string BtnEditActivitiesButton {
            get {
                return ResourceManager.GetString("BtnEditActivitiesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Cat..
        /// </summary>
        internal static string BtnEditDocumentCategories {
            get {
                return ResourceManager.GetString("BtnEditDocumentCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorities.
        /// </summary>
        internal static string BtnEditIssuePriorities {
            get {
                return ResourceManager.GetString("BtnEditIssuePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string BtnExitButton {
            get {
                return ResourceManager.GetString("BtnExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string BtnModifyButton {
            get {
                return ResourceManager.GetString("BtnModifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string BtnNewIssueButton {
            get {
                return ResourceManager.GetString("BtnNewIssueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOKButton {
            get {
                return ResourceManager.GetString("BtnOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string BtnRefreshButton {
            get {
                return ResourceManager.GetString("BtnRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string BtnResetButton {
            get {
                return ResourceManager.GetString("BtnResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnSaveButton {
            get {
                return ResourceManager.GetString("BtnSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string BtnSettingsButton {
            get {
                return ResourceManager.GetString("BtnSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string BtnStartButton {
            get {
                return ResourceManager.GetString("BtnStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string BtnStartButton_Pause {
            get {
                return ResourceManager.GetString("BtnStartButton_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string BtnTestConnection {
            get {
                return ResourceManager.GetString("BtnTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string cbDueDate {
            get {
                return ResourceManager.GetString("cbDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string cbStartDate {
            get {
                return ResourceManager.GetString("cbStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also close the issue.
        /// </summary>
        internal static string CheckBoxClosesIssue {
            get {
                return ResourceManager.GetString("CheckBoxClosesIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        internal static string CheckForUpdatesCheckBox {
            get {
                return ResourceManager.GetString("CheckForUpdatesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close issue {0}?.
        /// </summary>
        internal static string CloseIssueText {
            get {
                return ResourceManager.GetString("CloseIssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the new comment?.
        /// </summary>
        internal static string CommitCancelSaveCommentQuestion {
            get {
                return ResourceManager.GetString("CommitCancelSaveCommentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cancelled committing your spent time, but changed the comment.{0}Do you want to use the new comment?.
        /// </summary>
        internal static string CommitCancelSaveCommentText {
            get {
                return ResourceManager.GetString("CommitCancelSaveCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to commit?.
        /// </summary>
        internal static string CommitConfirmQuestion {
            get {
                return ResourceManager.GetString("CommitConfirmQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to commit the following entry: {6} Project: {0}, Activity: {1}, Issue: {2},{6}Date: {3}, Comment: {4}, Time: {5}.
        /// </summary>
        internal static string CommitConfirmText {
            get {
                return ResourceManager.GetString("CommitConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no activity selected..
        /// </summary>
        internal static string CommitNoActivitySelected {
            get {
                return ResourceManager.GetString("CommitNoActivitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no issue selected..
        /// </summary>
        internal static string CommitNoIssueSelected {
            get {
                return ResourceManager.GetString("CommitNoIssueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no time to log....
        /// </summary>
        internal static string CommitNoTime {
            get {
                return ResourceManager.GetString("CommitNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work logged successfully..
        /// </summary>
        internal static string CommitSuccessfullText {
            get {
                return ResourceManager.GetString("CommitSuccessfullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work logged.
        /// </summary>
        internal static string CommitSuccessfullTitle {
            get {
                return ResourceManager.GetString("CommitSuccessfullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating the connection with Redmine failed. The following error occurred: {0}.
        /// </summary>
        internal static string ConnectionTestFailed_Text {
            get {
                return ResourceManager.GetString("ConnectionTestFailed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test Failed.
        /// </summary>
        internal static string ConnectionTestFailed_Title {
            get {
                return ResourceManager.GetString("ConnectionTestFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating the connection with Redmine was successful..
        /// </summary>
        internal static string ConnectionTestOK_Text {
            get {
                return ResourceManager.GetString("ConnectionTestOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test Success.
        /// </summary>
        internal static string ConnectionTestOK_Title {
            get {
                return ResourceManager.GetString("ConnectionTestOK_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enumeration Value {0} for {1}.
        /// </summary>
        internal static string DlgEditEnumFormTitle_Edit {
            get {
                return ResourceManager.GetString("DlgEditEnumFormTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Enumeration Value for {0}.
        /// </summary>
        internal static string DlgEditEnumFormTitle_New {
            get {
                return ResourceManager.GetString("DlgEditEnumFormTitle_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enumeration {0}.
        /// </summary>
        internal static string DlgEditEnumListFormTitle {
            get {
                return ResourceManager.GetString("DlgEditEnumListFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Issue {0} for project {1}.
        /// </summary>
        internal static string DlgIssueTitleEdit {
            get {
                return ResourceManager.GetString("DlgIssueTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Issue for project {0}.
        /// </summary>
        internal static string DlgIssueTitleNew {
            get {
                return ResourceManager.GetString("DlgIssueTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string DlgSettingsTitle {
            get {
                return ResourceManager.GetString("DlgSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string EnumName_Activities {
            get {
                return ResourceManager.GetString("EnumName_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Categories.
        /// </summary>
        internal static string EnumName_DocumentCategories {
            get {
                return ResourceManager.GetString("EnumName_DocumentCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Priorities.
        /// </summary>
        internal static string EnumName_IssuePriorities {
            get {
                return ResourceManager.GetString("EnumName_IssuePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status used to close an issue is unknown, please go to settings to set this..
        /// </summary>
        internal static string Error_ClosedStatusUnknown {
            get {
                return ResourceManager.GetString("Error_ClosedStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the issue failed; The server responded: {0}.
        /// </summary>
        internal static string Error_CreateIssueFailed {
            get {
                return ResourceManager.GetString("Error_CreateIssueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}  is a mandatory field..
        /// </summary>
        internal static string Error_EnumFieldIsMandatory {
            get {
                return ResourceManager.GetString("Error_EnumFieldIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id and the Name must be unique..
        /// </summary>
        internal static string Error_EnumMustBeUnique {
            get {
                return ResourceManager.GetString("Error_EnumMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL of Redmine installation..
        /// </summary>
        internal static string Error_InvalidUrl {
            get {
                return ResourceManager.GetString("Error_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue subject is mandatory.
        /// </summary>
        internal static string Error_IssueSubjectMandatory {
            get {
                return ResourceManager.GetString("Error_IssueSubjectMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects found in Redmine..
        /// </summary>
        internal static string Error_NoProjectsFound {
            get {
                return ResourceManager.GetString("Error_NoProjectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup error. Check Configuration..
        /// </summary>
        internal static string Error_Startup {
            get {
                return ResourceManager.GetString("Error_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the issue failed; The server responded: {0}.
        /// </summary>
        internal static string Error_UpdateIssueFailed {
            get {
                return ResourceManager.GetString("Error_UpdateIssueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value out of range.
        /// </summary>
        internal static string Error_ValueOutOfRange {
            get {
                return ResourceManager.GetString("Error_ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string GrpApplicationSettings {
            get {
                return ResourceManager.GetString("GrpApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enumerations.
        /// </summary>
        internal static string GrpEditEnumerations {
            get {
                return ResourceManager.GetString("GrpEditEnumerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Server Settings.
        /// </summary>
        internal static string GrpRedmineServerSettings {
            get {
                return ResourceManager.GetString("GrpRedmineServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string labelActivity {
            get {
                return ResourceManager.GetString("labelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        internal static string labelAssignedTo {
            get {
                return ResourceManager.GetString("labelAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache lifetime (minutes, 0 = infinite).
        /// </summary>
        internal static string labelCacheLifetime {
            get {
                return ResourceManager.GetString("labelCacheLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string labelComment {
            get {
                return ResourceManager.GetString("labelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity:.
        /// </summary>
        internal static string labelCommitActivity {
            get {
                return ResourceManager.GetString("labelCommitActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string labelCommitComment {
            get {
                return ResourceManager.GetString("labelCommitComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent on:.
        /// </summary>
        internal static string labelCommitDateSpent {
            get {
                return ResourceManager.GetString("labelCommitDateSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue:.
        /// </summary>
        internal static string labelCommitIssue {
            get {
                return ResourceManager.GetString("labelCommitIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        internal static string labelCommitProject {
            get {
                return ResourceManager.GetString("labelCommitProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to commit the following time entry?.
        /// </summary>
        internal static string labelCommitQuestion {
            get {
                return ResourceManager.GetString("labelCommitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (H):.
        /// </summary>
        internal static string labelCommitTime {
            get {
                return ResourceManager.GetString("labelCommitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string labelEnumId {
            get {
                return ResourceManager.GetString("labelEnumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string labelEnumName {
            get {
                return ResourceManager.GetString("labelEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        internal static string labelEstimatedTime {
            get {
                return ResourceManager.GetString("labelEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable field with &apos;Test Connection&apos; and version V1.3.x or higher.
        /// </summary>
        internal static string labelExplClosingIssueStatus {
            get {
                return ResourceManager.GetString("labelExplClosingIssueStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string labelLanguage {
            get {
                return ResourceManager.GetString("labelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Done.
        /// </summary>
        internal static string labelPercentDone {
            get {
                return ResourceManager.GetString("labelPercentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup window when minimized
        ///or Request attention every
        ///(minutes, 0 = never).
        /// </summary>
        internal static string labelPopupTimout {
            get {
                return ResourceManager.GetString("labelPopupTimout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string labelPriority {
            get {
                return ResourceManager.GetString("labelPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string labelProject {
            get {
                return ResourceManager.GetString("labelProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine password.
        /// </summary>
        internal static string labelRedminePassword {
            get {
                return ResourceManager.GetString("labelRedminePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine URL.
        /// </summary>
        internal static string labelRedmineURL {
            get {
                return ResourceManager.GetString("labelRedmineURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine username.
        /// </summary>
        internal static string labelRedmineUsername {
            get {
                return ResourceManager.GetString("labelRedmineUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Version.
        /// </summary>
        internal static string labelRedmineVersion {
            get {
                return ResourceManager.GetString("labelRedmineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When closing an Issue, set it to.
        /// </summary>
        internal static string labelSelectCloseStatus {
            get {
                return ResourceManager.GetString("labelSelectCloseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string labelSubject {
            get {
                return ResourceManager.GetString("labelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Version.
        /// </summary>
        internal static string labelTargetVersion {
            get {
                return ResourceManager.GetString("labelTargetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        internal static string labelTracker {
            get {
                return ResourceManager.GetString("labelTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this issue in Redmine.
        /// </summary>
        internal static string linkEditInRedmine {
            get {
                return ResourceManager.GetString("linkEditInRedmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on start timer.
        /// </summary>
        internal static string MinimizeOnStartTimerCheckBox {
            get {
                return ResourceManager.GetString("MinimizeOnStartTimerCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to systemtray.
        /// </summary>
        internal static string MinimizeToSystemTrayCheckBox {
            get {
                return ResourceManager.GetString("MinimizeToSystemTrayCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available. Do you want me to take you to the download location?.
        /// </summary>
        internal static string NewVersionText {
            get {
                return ResourceManager.GetString("NewVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersionTitle {
            get {
                return ResourceManager.GetString("NewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Client.
        /// </summary>
        internal static string RedmineClientTitle_NoUser {
            get {
                return ResourceManager.GetString("RedmineClientTitle_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Client - {0} {1}.
        /// </summary>
        internal static string RedmineClientTitle_User {
            get {
                return ResourceManager.GetString("RedmineClientTitle_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string RestoreToolStrip_Hide {
            get {
                return ResourceManager.GetString("RestoreToolStrip_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi&amp;nimize.
        /// </summary>
        internal static string RestoreToolStrip_Minimize {
            get {
                return ResourceManager.GetString("RestoreToolStrip_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore.
        /// </summary>
        internal static string RestoreToolStrip_Restore {
            get {
                return ResourceManager.GetString("RestoreToolStrip_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Redmine Client is trying to stop, but you are measuring your spent time.{0}Do you want to commit the time?.
        /// </summary>
        internal static string Warning_ClosingSaveTimes {
            get {
                return ResourceManager.GetString("Warning_ClosingSaveTimes", resourceCulture);
            }
        }
    }
}
